---
# cluster_name is used to group the nodes in a folder within VirtualBox:
cluster_name: Kubernetes Cluster
# Uncomment to set environment variables for services such as crio and kubelet.
# For example, configure the cluster to pull images via a proxy.
# environment: |
#   HTTP_PROXY=http://my-proxy:8000
#   HTTPS_PROXY=http://my-proxy:8000
#   NO_PROXY=127.0.0.1,localhost,master-node,node01,node02,node03
# All IPs/CIDRs should be private and allowed in /etc/vbox/networks.conf.

network:
  dns_server: 8.8.8.8
  pod_cidr: 10.244.0.0/16
  service_cidr: 172.17.1.0/18

nodes:
  control:
    hostname: control
    cpu: 2
    memory: 4096
    ip: 192.168.56.100
  worker:
    hostname: worker
    count: 2
    cpu: 1
    memory: 2048
    ip_prefix: 192.168.56.10

software:
  box: ubuntu/focal64
  calico: 3.25.0
  kubernetes: 1.27.3-00
  kubernetes_version: 1.27.3
#  os: xUbuntu_22.04